apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: vpa-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app
        image: vish/stress
        args:
        - -cpus
        - "1"
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"