apiVersion: v1
kind: Service
metadata:
  name: kubia-lb
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
    - port: 8080
      targetPort: 8080
  externalIPs:
    - 10.0.0.4  # Your JumpHost/HAProxy IP