apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-ingress
  namespace: demo-app
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: demo-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # MUST be <namespace>-<name>@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: demo-app-web-ingress@kubernetescrd
spec:
  rules:
    ## Change the XX to your student number
  - host: web.app.stuXX.steven.asia
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  tls:
  - hosts:
  ## Change the XX to your student number
    - web.app.stuXX.steven.asia
    secretName: web-tls