apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-db
  namespace: servicemesh-ns
  labels:
    app: videos-db
spec:
  selector:
    matchLabels:
      app: videos-db
  replicas: 1
  template:
    metadata:
      labels:
        app: videos-db
    spec:
      containers:
      - name: videos-db
        image: stv707/dataredis:6.0-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: videos-db
  namespace: servicemesh-ns
  labels:
    app: videos-db
spec:
  type: ClusterIP
  selector:
    app: videos-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379