apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: videos-web-rewrite
  namespace: servicemesh-ns
spec:
  replacePathRegex:
    regex: "^/home(/|$)(.*)"
    replacement: "/$2"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: videos-web-https-redirect
  namespace: servicemesh-ns
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: videos-web
  namespace: servicemesh-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: servicemesh-ns-videos-web-rewrite@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: servicemesh-ns-videos-web-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: mesh.app.stu07.steven.asia
    http:
      paths:
      - path: /home/
        pathType: Prefix
        backend:
          service:
            name: videos-web
            port:
              number: 80
  tls:
  - hosts:
    - mesh.app.stu07.steven.asia # 🔁 Replace stuXX
    secretName: servicemesh-tls
