---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: servicemesh-https-redirect
  namespace: servicemesh-ns
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicemesh-ingress
  namespace: servicemesh-ns
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: servicemesh-ns-servicemesh-https-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: servicemesh.app.stuXX.steven.asia  # 🔁 Replace stuXX
    http:
      paths:
      - path: /home(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: videos-web
            port:
              number: 80
  tls:
  - hosts:
    - servicemesh.app.stuXX.steven.asia # 🔁 Replace stuXX
    secretName: servicemesh-tls


####OLD####
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: servicemesh-ns
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: servicemesh.demo
#     http:
#       paths:
#       - path: /home(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: servicemesh-ns
#             port:
#               number: 80