apiVersion: v1
kind: Pod
metadata:
  name: inspector-pod
  namespace: devspace
spec:
  serviceAccountName: inspector
  containers:
  - name: inspector
    image: bitnami/kubectl
    command: ["sleep", "3600"]
