apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - name: kubia
    image: stv707/kubia:v14
    ports:
    - containerPort: 8080
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      seccompProfile:
       type: RuntimeDefault
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000