apiVersion: v1
kind: Pod
metadata:
  name: escalate-pod
spec:
  containers:
  - name: kubia
    image: stv707/kubia:v14
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: true