apiVersion: v1
kind: ReplicationController
metadata:
  name: kubiared
  namespace: redblue
spec:
  replicas: 2
  selector:
    app: kubiared
  template:
    metadata:
      labels:
        app: kubiared
    spec:
      containers:
      - name: kubiared
        image: stv707/kubiared
        ports:
        - containerPort: 8080
