apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubiaredblue
  namespace: redblue
  annotations:
   traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    ## Change XX to your Student Number 
  - host: color.app.stuXX.steven.asia
    http:
      paths:
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: kubiablue
            port: 
              number: 80
              
    # Change XX to your Student Number           
  - host: color.app.stuXX.steven.asia
    http:          
      paths:
      - path: /red
        pathType: Prefix
        backend:
          service:
            name: kubiared
            port: 
              number: 80