apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-backend-vote
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-backend-vote
  template:
    metadata:
      labels:
        app: app1-backend-vote
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: app1-backend-vote
        image: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis